GET http://localhost:8080/users HTTP/1.1

###

GET http://localhost:8080/users/1 HTTP/1.1

###

POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "name": "Daniel",
    "email": "daniel.dr206@gmail.com"
}
###

DELETE http://localhost:8080/users/1 HTTP/1.1
###

PUT http://localhost:8080/users/2 HTTP/1.1
content-type: application/json

{
    "name": "x",
    "email": "x@gmail.com"
}
###


